version: '3.8'

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8081:28852"
    container_name: app
    depends_on:
      - db
  db:
    image: postgres:11.17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: service_db
      POSTGRES_PASSWORD: JtM0hLhgt-=2